name: marp-to-pages
concurrency: marp-to-pages

env:
  MARP_CLI_VERSION: 4.4.0

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Install and Build 🔧
        run: |
            npm install -g @marp-team/marp-cli@${{ env.MARP_CLI_VERSION }}
            marp --theme theme/blavad.css presentation.md --html -o ./public/index.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public # The folder the action should deploy.
